# Generated by Django 3.0.6 on 2020-06-09 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=50)),
                ('request_title', models.CharField(max_length=150)),
                ('request_content', models.TextField()),
                ('date_requested', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='Firstname', max_length=50)),
                ('member_id', models.CharField(max_length=10, null=True, unique=True)),
                ('resident_address', models.CharField(blank=True, default='Not Specified', max_length=100)),
                ('surname', models.CharField(default='Surname', max_length=50)),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now)),
                ('date_added', models.DateField(auto_now=True)),
                ('region', models.CharField(default='Region', max_length=50)),
                ('phone_number', models.CharField(max_length=10, null=True, unique=True)),
                ('image', models.ImageField(default='user_image.png', upload_to='profile_images')),
                ('gender', models.CharField(default='Gender', max_length=10)),
                ('wing_name', models.CharField(default='Not Provided', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('date_posted', models.DateField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
